truncate table roles cascade;
truncate table users cascade;
truncate table user_roles cascade;
truncate table localities cascade;
truncate table regions cascade;
truncate table countries cascade;
truncate table region_localities cascade;
truncate table country_regions cascade;
truncate table addresses cascade;